version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: rov_db
    environment:
      POSTGRES_USER: rov_user
      POSTGRES_PASSWORD: rov_password
      POSTGRES_DB: rov_database
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
